### ISSUE TITLE
Tears Of The Kingdom Phive/Havok Research

### ISSUE THREAD

**Issue by MediaMoots** [The12thAvenger/HKLib#2]
Would it be possible to take a look at Tears of the kingdom's implementation of havok cloth, specifically the cloth list files.

From what i have found, the game has a wrapper called Phive that they use to wrap the havok tags.
Here are a couple of sample cloth list files.

[Armor_001_Head_A bphhb.zip](https://github.com/The12thAvenger/HKLib/files/12645747/Armor_001_Head_A.bphhb.zip)
[Armor_001_Head_A bphcl.zip](https://github.com/The12thAvenger/HKLib/files/12645749/Armor_001_Head_A.bphcl.zip)

bphcl = Binary PHive Cloth List
bphhb = Binary PHive Helper Bone

The game also references a hkt file loaded from somewhere in the bphcl

**Comment by The12thAvenger** [comment]
The bphcl does contain a Havok Tagfile at offset 0x30 and also an AAMP file, the bphhb seems to be just an AAMP file.
ToTK apparently uses Havok 2022 which at a glance doesn't seem any different from Havok 2019 in terms of the file format. I have looked at the differences between 2018 (the only version I currently have implemented) and 2019 and it should be fairly simple to implement support for the newer versions. 

However, as HKLib aims to provide a strongly typed interface to the data through source generation, support for any new version/platform would require a relevant type registry. I recently wrote a dll that when injected into a PC game would grab the type information at runtime however I have no such solution for the switch and am not familiar with switch modding in general.

If you can provide such a type registry or a memory dump from which I could extract one I can add support for ToTK havok files when I finish rewriting the source generator. Alternatively you could also use [Tagtools/Havoc](https://github.com/blueskythlikesclouds/TagTools) which I've heard has worked for Havok 2019 although I don't know which fork and whether or not any edits to the code were required.

**Comment by MediaMoots** [comment]
Ok cool.
What information is stored in a type registry?

**Comment by MediaMoots** [comment]
[totk_hktypeinfo_1.0.0_sort (1).txt](https://github.com/The12thAvenger/HKLib/files/12661273/totk_hktypeinfo_1.0.0_sort.1.txt)
I found this, but i don't know if its useful

**Comment by The12thAvenger** [comment]
This is the [type registry](https://github.com/The12thAvenger/HKLib/blob/main/HKLib.Reflection/Res/HavokTypeRegistry20180100.xml) for 2018. Basically a description of memory layout of every data type.
What you posted seems to be a list of the type names which by itself is not enough.

**Comment by The12thAvenger** [comment]
note that this is a custom format I use for HKLib. You won't find a direct equivalent. the necessary type information is stored in the game executable and of course in the files.

**Comment by MediaMoots** [comment]
@The12thAvenger Gotcha.
I wasn't able to get a type registry yet, but i got a memory dump and the game exe (called main)
Here they are, lmk if that's enough info.
https://drive.google.com/file/d/1-b0v-35IjyYfN5v8P5_cwchAeO1FQ6pL/view?usp=sharing

**Comment by The12thAvenger** [comment]
That should be enough, thank you

**Comment by MediaMoots** [comment]
@The12thAvenger 
Cool! Thank you. If you need anything else, please lmk.
Do you know if these files could eventually be previewed in the Havok Preview Tool 2018 (or whatever is latest)?
The goal would be to create completely new physics, is that possible?
I think changing colliders or tweaking settings would be quite straight forward, but i was wondering if you know of ways to create new physics.

**Comment by The12thAvenger** [comment]
You'd need to manage conversion between the game version and whatever version of the content tools you have. The kinds of physics you can create depend on your content tools installation.

**Comment by MediaMoots** [comment]
@The12thAvenger Whats the latest version of content tools that are available?

**Comment by MediaMoots** [comment]
Also, my main 3d software is blender, so i would need to write an addon for that.

**Comment by MediaMoots** [comment]
What would be a possible workflow?
Use HKLib to convert bpchl to a text format (maybe json), edit with a custom addon in blender, and finally use HKLib to convert back to bphcl?
Does that sound correct? Or is there a better way to do things?

**Comment by The12thAvenger** [comment]
I don’t think this is really the place to discuss this in detail. You can contact me on discord under the same username if you want.

**Comment by MediaMoots** [comment]
Ok, i sent a friend request, thanks!
